CAP01 - INTRODUÇÃO
CAP02 - VARÁVEIS,TIPOS E ESTRUTURAS DE DADOS
CAP03 - LOOPS, CONDICIONAIS, MÉTODOS E FUNÇÕES
CAP04 - TRATAMENTO DE ARQUIVOS, MÓDULOS E PACOTES
CAP05 - ORIENTAÇÃO A OBJETOS
CAP06 - MANIPULANDO BANCO DE DADOS EM PYTHON
CAP07 - DESAFIO DSA
CAP08 - MÓDULOS PYTHON PARA ANALISE DE DADOS
CAP09-   INTRODUÇÃO À ANALISE DE DADOS  COM PYTHON
CAP10 - INTRODUÇÃO AO TENSORFLOW
CAP11 - INTRODUCAO A MACHINE LEARNING COM PYTHON
CAP12 - BÔNUS - INTRODUÇÃO A DEEP LEARNING
CAP13 - DESENVOLVIMENTO WEB
CAP14 - INTRODUÇÃO AO WEB SCRAPING
CAP15 - AVALIAÇÃO FINAL E CERTIFICADO DE CONCLUSÃO